DPWEBCORE-908 Add styles to Front-End in line with Figma assets
bbc/status pull request #31
Opened 2020-09-09 16:27 UTC by MattLongCode

@bbc/web-core-devx

# Problem

-   Status page has no styles.
-   Wider context: https://jira.dev.bbc.co.uk/browse/DPWEBCORE-908

# Solution

- Add styles

2020-09-09 16:35 UTC, abrarkhan1234 commented on src/app/App.tsx
> +  });
Missed this out in my commit
`}, []);`

2020-09-09 16:35 UTC, abrarkhan1234 commented on src/app/App.tsx
> +  });
This is so that fetchdata does not kick off infinitely.

2020-09-09 17:00 UTC, abrarkhan1234 commented on src/app/App.tsx
> +`}, []);`
didn't mean for the ticks to be part of the code:
```suggestion
}, []);
```

2020-09-09 17:03 UTC, abrarkhan1234 commented on src/app/App.tsx
> +      <RunBooks />
Just a design preference, can we have capabilities and platforms shunted to the top and runbooks just before the past incidents? Theres more value in the statuses of the service than the runbook links.

2020-09-09 17:04 UTC, abrarkhan1234 commented on src/app/Capabilities.tsx
> +              <h2>Homepage</h2>
Been a long time since i worked with the gel grid, but just a thought, there's a lot of nesting here, is there any chance some of this can be removed?

2020-09-09 17:04 UTC, abrarkhan1234 approved these changes
I ran this locally and it looks delightful!! Couple of wee comments but nothing blocking.

2020-09-09 17:05 UTC, abrarkhan1234 commented
Can we bump the version?

2020-09-09 17:31 UTC, abrarkhan1234 commented on src/app/RunBooks.tsx
> +//   <section className="gel-wrap">
Can we remove all these commented out lines...

2020-09-09 17:36 UTC, abrarkhan1234 commented
Seems like all asset files are camel case but this, `src/app/images/banner-background.png` can we rename to match naming style.

2020-09-10 08:50 UTC, benwainwright requested changes

2020-09-10 08:50 UTC, benwainwright commented on package.json
> -      "<rootDir>/src/setupTests.ts"
Why has this been removed from the config?

2020-09-10 08:50 UTC, benwainwright commented on src/app/App.tsx
> +      <div className="status-panel">
Why this div? Can we have all markup related to a given component encapsulated within that component please

2020-09-10 08:50 UTC, benwainwright commented on src/app/Capabilities.tsx
> +              <h2>Homepage</h2>
Yeah, I was wondering this...

2020-09-10 08:50 UTC, benwainwright commented on src/app/Capabilities.tsx
> +  <div className="gel-wrap">
Semantically surely this should be a table, rather than a series of nested divs?

2020-09-10 08:50 UTC, benwainwright commented on src/app/Header.tsx
> +  <div className="gel-wrap">
Can we use the HTML `header` tag in headers please

2020-09-10 08:50 UTC, benwainwright commented on src/app/Banner.tsx
> +          <h2>Operational</h2>
Semantically this doesn't make sense as an `h2` tag - it's not a header

2020-09-10 08:50 UTC, benwainwright commented on src/app/Platforms.tsx
> +  <div className="gel-wrap">
The `Capabilities` and `Platforms` components are basically the same thing aren't they - they are data tables.

We need to be using html `table` tags rather than nested divs otherwise it's going to be horrible for a11y. Should we not write a generic component that 

- Takes in data
- Has a header
- Renders an arbitrary number of rows based on the data

And then use them in both instances?

2020-09-10 08:53 UTC, benwainwright commented on src/app/RunBooks.tsx
> +//   <section className="gel-wrap">
Yes please

2020-09-10 08:56 UTC, benwainwright commented
I've tried to run this and I get the following error when I do `yarn install && yarn start`

![image](https://user-images.githubusercontent.com/3321885/92705846-f06d1980-f34b-11ea-8b9c-2c6a19d8d929.png)

2020-09-10 09:57 UTC, MattLongCode commented on package.json
> -      "<rootDir>/src/setupTests.ts"
There was a pre commit error, similar to this message:

```
husky > pre-commit (node v12.14.0)
✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *.{js,jsx,ts,tsx}
    ✔ eslint
    ✔ prettier --write
    ✖ react-scripts test --watchAll=false --findRelatedTests [FAILED]
  ↓ No staged files match *.json [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ react-scripts test --watchAll=false --findRelatedTests:

Out of the box, Create React App only supports overriding these Jest options:

  • clearMocks
  • collectCoverageFrom
  • coveragePathIgnorePatterns
  • coverageReporters
  • coverageThreshold
  • displayName
  • extraGlobals
  • globalSetup
  • globalTeardown
  • moduleNameMapper
  • resetMocks
  • resetModules
  • restoreMocks
  • snapshotSerializers
  • transform
  • transformIgnorePatterns
  • watchPathIgnorePatterns.

These options in your package.json Jest configuration are not currently supported by Create React App:

  • roots
  • setupFiles
  • testMatch
  • testEnvironment
  • modulePaths
  • moduleFileExtensions
  • watchPlugins

If you wish to override other Jest options, you need to eject from the default setup. You can do so by running npm run eject but remember that this is a one-way operation. You may also file an issue with Create React App to discuss supporting more options out of the box.

husky > pre-commit hook failed (add --no-verify to bypass)
error Command failed with exit code 1.
```

I removed these lines to begin resolving the error.

2020-09-10 10:44 UTC, abrarkhan1234 commented on src/app/Capabilities.tsx
> +              <h2>Homepage</h2>
We are removing this component from being rendered so resolving, will revisit this code once we implement the figma design.

2020-09-10 10:55 UTC, abrarkhan1234 commented on src/app/Capabilities.tsx
> +  <div className="gel-wrap">
As agreed at standup to get this shipped for tomorrow we will eep as is and will revisit the semantics once we work on the real design.

2020-09-10 10:58 UTC, abrarkhan1234 commented on src/app/Header.tsx
> +  <div className="gel-wrap">
Good shout! done!

2020-09-10 11:00 UTC, abrarkhan1234 commented on src/app/Platforms.tsx
> +  <div className="gel-wrap">
Completely agreed but as discussed above, we will revisit the semantics when implementing the real design.

2020-09-10 15:45 UTC, merged